### ISSUE TITLE
Do you know why cloudflare is giving me this issue? 

### ISSUE THREAD

**Issue by Parthvsquare** [zankhq/astros#33]
I am importing NewsLetter.astro. local build is working on both macos and windows. 
```bash
2023-10-29T20:49:25.977166Z	Cloning repository...
2023-10-29T20:49:27.383549Z	From https://github.com/Parthvsquare/astro_dummy
2023-10-29T20:49:27.384268Z	 * branch            b0e59da503007c5cf006de2848058436d0501bed -> FETCH_HEAD
2023-10-29T20:49:27.384464Z	
2023-10-29T20:49:27.605025Z	HEAD is now at b0e59da fix: newletter
2023-10-29T20:49:27.605901Z	
2023-10-29T20:49:27.71448Z	
2023-10-29T20:49:27.745771Z	Success: Finished cloning repository files
2023-10-29T20:49:28.620114Z	Detected the following tools from environment: npm@9.6.7, nodejs@18.17.1
2023-10-29T20:49:28.620986Z	Installing project dependencies: npm clean-install --progress=false
2023-10-29T20:49:33.473848Z	npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
2023-10-29T20:49:33.515907Z	npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
2023-10-29T20:49:36.609531Z	npm WARN deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser
2023-10-29T20:49:41.935274Z	
2023-10-29T20:49:41.936939Z	added 936 packages, and audited 937 packages in 12s
2023-10-29T20:49:41.937308Z	
2023-10-29T20:49:41.937519Z	285 packages are looking for funding
2023-10-29T20:49:41.937677Z	  run `npm fund` for details
2023-10-29T20:49:41.952922Z	
2023-10-29T20:49:41.954025Z	5 low severity vulnerabilities
2023-10-29T20:49:41.954492Z	
2023-10-29T20:49:41.955645Z	To address issues that do not require attention, run:
2023-10-29T20:49:41.955995Z	  npm audit fix
2023-10-29T20:49:41.956513Z	
2023-10-29T20:49:41.956841Z	To address all issues (including breaking changes), run:
2023-10-29T20:49:41.957014Z	  npm audit fix --force
2023-10-29T20:49:41.957189Z	
2023-10-29T20:49:41.957335Z	Run `npm audit` for details.
2023-10-29T20:49:41.978247Z	Executing user command: npm run build
2023-10-29T20:49:42.827443Z	
2023-10-29T20:49:42.827778Z	> astros@1.0.1 build
2023-10-29T20:49:42.827955Z	> astro build
2023-10-29T20:49:42.828109Z	
2023-10-29T20:49:45.723108Z	08:49:45 PM [content] The "team" collection does not have an associated folder in your `content` directory. Make sure the folder exists, or check your content config for typos.
2023-10-29T20:49:45.724026Z	08:49:45 PM [content] Types generated 594ms
2023-10-29T20:49:45.725331Z	08:49:45 PM [build] output target: static
2023-10-29T20:49:45.72577Z	08:49:45 PM [build] Collecting build info...
2023-10-29T20:49:45.728409Z	08:49:45 PM [build] Completed in 731ms.
2023-10-29T20:49:45.730695Z	08:49:45 PM [build] Building static entrypoints...
2023-10-29T20:49:49.088389Z	[31m[vite-plugin-pwa:build] [vite]: Rollup failed to resolve import "@components/NewsLetter.astro" from "/opt/buildhome/repo/src/pages/vuestorefront-headless-ecommerce.astro".
2023-10-29T20:49:49.088797Z	This is most likely unintended because it can break your application at runtime.
2023-10-29T20:49:49.089081Z	If you do want to externalize this module explicitly add it to
2023-10-29T20:49:49.08949Z	`build.rollupOptions.external`[39m
2023-10-29T20:49:49.422038Z	 error   [vite]: Rollup failed to resolve import "@components/NewsLetter.astro" from "/opt/buildhome/repo/src/pages/vuestorefront-headless-ecommerce.astro".
2023-10-29T20:49:49.422543Z	  This is most likely unintended because it can break your application at runtime.
2023-10-29T20:49:49.423063Z	  If you do want to externalize this module explicitly add it to
2023-10-29T20:49:49.423533Z	  `build.rollupOptions.external`
2023-10-29T20:49:49.423741Z	Error: [vite]: Rollup failed to resolve import "@components/NewsLetter.astro" from "/opt/buildhome/repo/src/pages/vuestorefront-headless-ecommerce.astro".
2023-10-29T20:49:49.423891Z	This is most likely unintended because it can break your application at runtime.
2023-10-29T20:49:49.424028Z	If you do want to externalize this module explicitly add it to
2023-10-29T20:49:49.42418Z	`build.rollupOptions.external`
2023-10-29T20:49:49.424311Z	    at viteWarn (file:///opt/buildhome/repo/node_modules/vite/dist/node/chunks/dep-df561101.js:48142:27)
2023-10-29T20:49:49.424446Z	    at onwarn (file:///opt/buildhome/repo/node_modules/@vitejs/plugin-react/dist/index.mjs:247:9)
2023-10-29T20:49:49.424582Z	    at onRollupWarning (file:///opt/buildhome/repo/node_modules/vite/dist/node/chunks/dep-df561101.js:48171:9)
2023-10-29T20:49:49.424724Z	    at onwarn (file:///opt/buildhome/repo/node_modules/vite/dist/node/chunks/dep-df561101.js:47902:13)
2023-10-29T20:49:49.424858Z	    at file:///opt/buildhome/repo/node_modules/rollup/dist/es/shared/node-entry.js:24194:13
2023-10-29T20:49:49.424993Z	    at Object.logger [as onLog] (file:///opt/buildhome/repo/node_modules/rollup/dist/es/shared/node-entry.js:25867:9)
2023-10-29T20:49:49.425163Z	    at ModuleLoader.handleInvalidResolvedId (file:///opt/buildhome/repo/node_modules/rollup/dist/es/shared/node-entry.js:24780:26)
2023-10-29T20:49:49.425309Z	    at file:///opt/buildhome/repo/node_modules/rollup/dist/es/shared/node-entry.js:24740:26
2023-10-29T20:49:49.459519Z	Failed: Error while executing user command. Exited with error code: 1
2023-10-29T20:49:49.481444Z	Failed: build command exited with code: 1
2023-10-29T20:49:50.428347Z	Failed: error occurred while running build command```

i got this log in cloudflare

**Comment by zanhk** [comment]
Hi,

From the log look like you are developing on windows and tried importing the NewsLetter component using `@components/NewsLetter.astro`, if its that the problem is that you are writing NewsLetter.astro instead of `newsletter.astro`.

Linux is case sensitive while windows is not.

**Comment by Parthvsquare** [comment]
turns out i changed their names to `EmailForm.astro` and its now working 👍🏼
