### ISSUE TITLE
TypeError - esm/i18next.js error - Cannot read properties of undefined (reading 'toResolveHierarchy')

### ISSUE THREAD

**Issue by captain0jay** [zankhq/astros#39]
Error details:- 

TypeError: Cannot read properties of undefined (reading 'toResolveHierarchy')
    at setLngProps (file:///E:/jay/codestuff/NewProjects/ProjectAd/Landingpage/astros/node_modules/i18next/dist/esm/i18next.js:2262:58)
    at setLng (file:///E:/jay/codestuff/NewProjects/ProjectAd/Landingpage/astros/node_modules/i18next/dist/esm/i18next.js:2288:13)
    at I18n.changeLanguage (file:///E:/jay/codestuff/NewProjects/ProjectAd/Landingpage/astros/node_modules/i18next/dist/esm/i18next.js:2306:9)
    at E:\jay\codestuff\NewProjects\ProjectAd\Landingpage\astros\src\pages\index.astro:10:1
    at index (E:\jay\codestuff\NewProjects\ProjectAd\Landingpage\astros\node_modules\astro\dist\runtime\server\astro-component.js:18:12)
    at callComponentAsTemplateResultOrResponse (file:///E:/jay/codestuff/NewProjects/ProjectAd/Landingpage/astros/node_modules/astro/dist/runtime/server/render/astro/render.js:85:31)
    at renderToReadableStream (file:///E:/jay/codestuff/NewProjects/ProjectAd/Landingpage/astros/node_modules/astro/dist/runtime/server/render/astro/render.js:35:32)
    at renderPage (file:///E:/jay/codestuff/NewProjects/ProjectAd/Landingpage/astros/node_modules/astro/dist/runtime/server/render/page.js:29:18)
    at renderPage (file:///E:/jay/codestuff/NewProjects/ProjectAd/Landingpage/astros/node_modules/astro/dist/core/render/core.js:45:26)
    at #tryRenderRoute (file:///E:/jay/codestuff/NewProjects/ProjectAd/Landingpage/astros/node_modules/astro/dist/core/pipeline.js:99:24)

![Screenshot (96)](https://github.com/zankhq/astros/assets/72175165/4226e37c-836d-4d28-b58a-22429f8908de)

**Comment by captain0jay** [comment]
i cloned it again and still the same error arises.
![Screenshot (97)](https://github.com/zankhq/astros/assets/72175165/23399daa-6e59-4e5f-9600-e5348485e372)

**Comment by captain0jay** [comment]
update: i deleted the repo , tried cloning again and ran it . Previous error went away but new one popped up 
![image](https://github.com/zankhq/astros/assets/72175165/e09d1c17-c2e4-46f4-8493-556ed7cb7810)

**Comment by captain0jay** [comment]
seems like the problem is with changeLanguage("in") in "\src\pages\index.astro:10:1" cant figure out what tho

**Comment by captain0jay** [comment]
Update:- When i am deploying the project after forking it works like a charm but locally its giving me errors. Its fine coz my initial task was accomplished but it would be really nice if i got a closure on why locally it gave me error. Also thanks for the beautiful looking website, really appreciate your work.

**Comment by zanhk** [comment]
Where do you run the project when you fork it?

**Comment by zanhk** [comment]
Closing as no updates
